/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{html,ts}", "./node_modules/flowbite/**/*.js"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#ECECFD",
          100: "#DADAFC",
          200: "#B4B4F8",
          300: "#8F8FF5",
          400: "#6969F1",
          500: "#4343EE",
          600: "#1414E0",
          700: "#0F0FA8",
          800: "#0A0A70",
          900: "#050538",
          950: "#03031C",
        },
        light: {
          50: "#FFFFFF",
          100: "#FCFCFC",
          200: "#FAFAFA",
          300: "#F7F7F7",
          400: "#F2F2F2",
          500: "#F0F0F0",
          600: "#EBEBEB",
          700: "#BDBDBD",
          800: "#8C8C8C",
          900: "#5E5E5E",
          950: "#2E2E2E",
        },
        dark: {
          50: "#EAEAEB",
          100: "#D5D5D7",
          200: "#A9A9AD",
          300: "#7F7F85",
          400: "#555559",
          500: "#2D2D2F",
          600: "#232324",
          700: "#1B1B1D",
          800: "#111112",
          900: "#0A0A0A",
          950: "#050505",
        },
        extra: {
          yellow: "#EBD669",
        },
      },
    },
    fontFamily: {
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
    },
  },
  plugins: [require("flowbite/plugin")],
};
